/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        ink: "hsl(var(--ink))",
        "ink-soft": "hsl(var(--ink-soft))",
        "ink-muted": "hsl(var(--ink-muted))",
        "ink-subtle": "hsl(var(--ink-subtle))",
        "line-soft": "hsl(var(--line-soft))",
        bone: "hsl(var(--bone))",
        air: "hsl(var(--air))",
        porcelain: "hsl(var(--porcelain))",
        studio: "hsl(var(--studio))",
        "studio-paper": "hsl(var(--studio-paper))",
        "studio-line": "hsl(var(--studio-line))",
        "studio-sunken": "hsl(var(--studio-sunken))",
        document: "hsl(var(--document))",
        "document-edge": "hsl(var(--document-edge))",
        "document-ink": "hsl(var(--document-ink))",
        "document-muted": "hsl(var(--document-muted))",
        "document-subtle": "hsl(var(--document-subtle))",
        rail: "hsl(var(--rail))",
        midnight: "hsl(var(--midnight))",
        "midnight-soft": "hsl(var(--midnight-soft))",
        "midnight-mark": "hsl(var(--midnight-mark))",
        "midnight-strong": "hsl(var(--midnight-strong))",
      },
    },
  },
  plugins: [],
}
